### ISSUE TITLE
Error message from lasso_train

### ISSUE THREAD

**Issue by joelager** [xraypy/xraylarch#500]
Running the example code from https://github.com/xraypy/xraylarch/tree/master/examples/xanes but with `lasso_train` instead of `pls_train`

```
 lasso_model = lasso_train(groups, arrayname='norm', varname='valence',
                          xmin=5430.0, xmax=5580.0, alpha=0.01,
                           fit_intercept=True, normalize=True)
```

Error message:
TypeError: LassoLars.__init__() got an unexpected keyword argument 'normalize'

This worked in previous versions but seems not to work in v0.9.74

**Comment by newville** [comment]
@joelager Thanks - I'll look into that.  I guess that there was some change in scikit-learn `Lasso` or `LassoLars` that we need to fix.

**Comment by joelager** [comment]
Yes, there has been a change:

Deprecated since version 1.0: normalize was deprecated in version 1.0 and will be removed in 1.2.

**Comment by newville** [comment]
@joelager Ah, yes, I see that too... not sure how long that has been a problem!  But, it also looks pretty straightforward to fix.
