### ISSUE TITLE
Anaconda subprocess error

### ISSUE THREAD

**Issue by meschw04** [xraypy/xraylarch#250]
I cloned the repo and ran setup.py, then got the following subprocess error:
```subprocess.CalledProcessError: Command '('/anaconda3/bin/python', '/anaconda3/bin/larch', '-m')' returned non-zero exit status 1.```
It looks like this was caused by the following import error:
```ImportError: Entry point ('console_scripts', 'larch') not found```

When I tried the conda install, I was able to successfully install the package but when I try to "import larch" in Python 3.6, I got the following error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/xraylarch-0.9.40-py3.6.egg/larch/__init__.py", line 32, in <module>
    from .larchlib import (plugin_path, use_plugin_path, enable_plugins,
  File "/anaconda3/lib/python3.6/site-packages/xraylarch-0.9.40-py3.6.egg/larch/larchlib.py", line 16, in <module>
    from .symboltable import Group, isgroup
  File "/anaconda3/lib/python3.6/site-packages/xraylarch-0.9.40-py3.6.egg/larch/symboltable.py", line 12, in <module>
    from . import site_config
  File "/anaconda3/lib/python3.6/site-packages/xraylarch-0.9.40-py3.6.egg/larch/site_config.py", line 43, in <module>
    os.makedirs(lshare, mode=oct(457)) # 457 = 7,1,1
  File "/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
TypeError: an integer is required (got type str)
```

It doesn't appear I'm missing a package, and I checked my versioning...not sure what the issue is.
Thanks for your help.

**Comment by newville** [comment]
@meschw04  Oh, thanks for that.  That is definitely a bug.  
 I'm surprised it didn't show up earlier -- I certainly use larch with Python3 on many different systems.

This is now fixed in the master repository.

**Comment by meschw04** [comment]
Hey @newville thanks for taking a look. Just uninstalled, reinstalled using conda. Download went without issue. However when I went into a console and tried to import, got the following error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/larch/__init__.py", line 28, in <module>
    from .shell import shell
  File "/anaconda3/lib/python3.6/site-packages/larch/shell.py", line 10, in <module>
    from .interpreter import Interpreter
  File "/anaconda3/lib/python3.6/site-packages/larch/interpreter.py", line 18, in <module>
    from . import builtins
  File "/anaconda3/lib/python3.6/site-packages/larch/builtins.py", line 22, in <module>
    from . import fitting
  File "/anaconda3/lib/python3.6/site-packages/larch/fitting/__init__.py", line 26, in <module>
    from lmfit import (Parameter, Parameters, Minimizer, conf_interval,
ImportError: cannot import name 'ufloat'
```
Tried it on my Windows 7 system (thought maybe it was a Mac thing), got the same issue.

**Comment by newville** [comment]
@meschw04 Sorry for the trouble.  I think that this is due to a stale `.../site_packages/larch` folder conflicting with a `.../site-packages/xraylarch-***.egg/` folder.   I think that if you just completely removing `site_packages/larch` it should then work, probably without even re-installing.

**Comment by meschw04** [comment]
So I uninstalled and reinstalled twice, making sure I'd deleted all eggs and larch-related files before re-downloading. Still getting that same error though.

**Comment by newville** [comment]
@meschw04   Oh, still sorry for the trouble.   Are you installing from github master branch or from the conda package or pip install?   I think it should work from github master (does for me), but I can see that the conda/pip packages won't work with lmfit 0.9.12.  Ugh, that's totally my fault, and self-inflicted.   I see that I need to update those (and release 0.9.41) very soon.  

OK, next thing to try: force installing lmfit 0.9.11 (previous version) with `pip install lmfit==0.9.11`.

**Comment by meschw04** [comment]
Awesome, that worked. Thanks Matt, closing this issue.
